<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * [mindpulse_quiz id="123"] shortcode and the mp_embed_quiz bare-page
 * route used by the B2B embed iframe (see MP_Embed).
 */
class MP_Shortcode {

	public static function register() {
		add_shortcode( 'mindpulse_quiz', array( __CLASS__, 'render' ) );
		add_shortcode( 'mindpulse_game', array( __CLASS__, 'render_game' ) );
		add_action( 'template_redirect', array( __CLASS__, 'maybe_render_embed_page' ) );
	}

	public static function render( $atts ) {
		$atts = shortcode_atts( array( 'id' => 0 ), $atts );
		return self::render_quiz( absint( $atts['id'] ), '' );
	}

	public static function render_game( $atts ) {
		$atts = shortcode_atts( array( 'id' => 0 ), $atts );
		$id   = absint( $atts['id'] );
		$url  = get_post_meta( $id, '_mp_game_embed_url', true );

		if ( ! $url ) {
			return '';
		}

		return sprintf(
			'<iframe src="%s" class="mp-game-frame" style="width:100%%;min-height:600px;border:0;"></iframe>',
			esc_url( $url )
		);
	}

	public static function render_quiz( $quiz_id, $partner_key ) {
		if ( ! $quiz_id || 'mp_quiz' !== get_post_type( $quiz_id ) ) {
			return '<p>' . esc_html__( 'Quiz not found.', 'mindpulse' ) . '</p>';
		}

		wp_enqueue_style( 'mp-frontend' );
		wp_enqueue_script( 'mp-quiz-runner' );

		$data = MP_CPT::get_quiz_data( $quiz_id );

		ob_start();
		?>
		<div class="mp-quiz"
			data-quiz-id="<?php echo esc_attr( $quiz_id ); ?>"
			data-partner-key="<?php echo esc_attr( $partner_key ); ?>"
			data-quiz='<?php echo esc_attr( wp_json_encode( $data ) ); ?>'>
			<div class="mp-quiz__loading"><?php esc_html_e( 'Loading quiz…', 'mindpulse' ); ?></div>
		</div>
		<?php
		return ob_get_clean();
	}

	/**
	 * Serves a bare (no theme chrome) page for ?mp_embed_quiz=ID, used
	 * inside the B2B iframe generated by embed.js.
	 */
	public static function maybe_render_embed_page() {
		if ( empty( $_GET['mp_embed_quiz'] ) ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended
			return;
		}

		$quiz_id     = absint( $_GET['mp_embed_quiz'] ); // phpcs:ignore WordPress.Security.NonceVerification.Recommended
		$partner_key = isset( $_GET['mp_partner_key'] ) ? sanitize_text_field( wp_unslash( $_GET['mp_partner_key'] ) ) : ''; // phpcs:ignore WordPress.Security.NonceVerification.Recommended

		wp_enqueue_style( 'mp-frontend' );
		wp_enqueue_script( 'mp-quiz-runner' );
		wp_print_styles( 'mp-frontend' );
		?>
		<!doctype html>
		<html>
		<head><meta charset="utf-8" /><title><?php echo esc_html( get_the_title( $quiz_id ) ); ?></title></head>
		<body class="mp-embed-body">
			<?php echo self::render_quiz( $quiz_id, $partner_key ); ?>
			<?php wp_print_scripts( 'mp-quiz-runner' ); ?>
		</body>
		</html>
		<?php
		exit;
	}
}
